/* auto-generated capacitor server stubs */
const _noop = async () => null;
export const createServerFn = () => {
  const f = async () => null;
  return Object.assign(f, { url: '', method() { return this; }, handler() { return this; }, inputValidator() { return this; }, middleware() { return this; } });
};
export const createMiddleware = () => ({ server: (h) => h });
export const createStartHandler = () => () => {};
export const getCookie = () => undefined;
export const setCookie = () => {};
export const getRequest = () => undefined;
export const getWebRequest = () => undefined;
export const getResponse = () => undefined;
export const getStartContext = () => ({});
export default {};
export const createPerson = _noop;
export const createSchoolUser = _noop;
export const dispatchPushToUser = _noop;
export const ensureLoginAccount = _noop;
export const getMyCbtResultServer = _noop;
export const getMyStudentContext = _noop;
export const getSchoolDashboardCounts = _noop;
export const hasAdminKey = _noop;
export const importStudentsBulk = _noop;
export const listSchoolApplications = _noop;
export const loginWithSchoolCode = _noop;
export const processExamReminders = _noop;
export const provisionStudentLogin = _noop;
export const reviewSchoolApplication = _noop;
export const saveCbtResultServer = _noop;
export const sendEmail = _noop;
export const sendSchoolApprovalEmail = _noop;
export const sendTestNotificationToSelf = _noop;
export const setApprovedSchoolAdminPassword = _noop;
export const signInWithSchoolCode = _noop;
export const studentAuthEmailCandidates = _noop;
export const supabaseAdmin = _noop;
export const upsertStudent = _noop;
export const writeLoginAudit = _noop;
