#!/usr/bin/env python3
"""Force-link Capacitor plugins after cap sync (prevents empty gradle / missing biometric)."""
from __future__ import annotations
import pathlib, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android"
NM = ROOT / "node_modules"
PLUGINS = [
    ("capacitor-app", "@capacitor/app/android"),
    ("capacitor-camera", "@capacitor/camera/android"),
    ("capacitor-local-notifications", "@capacitor/local-notifications/android"),
    ("capacitor-push-notifications", "@capacitor/push-notifications/android"),
    ("capacitor-splash-screen", "@capacitor/splash-screen/android"),
    ("capacitor-status-bar", "@capacitor/status-bar/android"),
    ("capgo-native-biometric", "@capgo/capacitor-native-biometric/android"),
]
def main() -> int:
    if not ANDROID.is_dir():
        print("WARN: no android/")
        return 0
    present = []
    for name, rel in PLUGINS:
        if (NM / rel).is_dir():
            present.append((name, rel))
        else:
            print(f"WARN: missing node_modules/{rel}")
    if not any(n == "capgo-native-biometric" for n, _ in present):
        print("FATAL: @capgo/capacitor-native-biometric/android missing")
        return 1
    settings = ANDROID / "capacitor.settings.gradle"
    lines = [
        "// GENERATED by scripts/ensure-capacitor-plugins.py",
        "include ':capacitor-android'",
        "project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')",
        "",
    ]
    for name, rel in present:
        lines.append(f"include ':{name}'")
        lines.append(f"project(':{name}').projectDir = new File('../node_modules/{rel}')")
        lines.append("")
    settings.write_text("\n".join(lines) + "\n")
    deps = "\n".join(f"    implementation project(':{name}')" for name, _ in present)
    (ANDROID / "app" / "capacitor.build.gradle").write_text(
        f"""// GENERATED by scripts/ensure-capacitor-plugins.py
android {{
  compileOptions {{
      sourceCompatibility JavaVersion.VERSION_21
      targetCompatibility JavaVersion.VERSION_21
  }}
}}
apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
dependencies {{
{deps}
}}
if (hasProperty('postBuildExtras')) {{
  postBuildExtras()
}}
"""
    )
    print("Linked:", ", ".join(n for n, _ in present))

    # Ensure AndroidX Biometric for D4NativeAuth BiometricPrompt
    app_bg = ANDROID / "app" / "build.gradle"
    if app_bg.is_file():
        bg = app_bg.read_text()
        if "androidx.biometric" not in bg:
            needle = 'implementation "androidx.appcompat:appcompat'
            if needle in bg:
                bg = bg.replace(
                    needle,
                    'implementation "androidx.biometric:biometric:1.1.0"\n    ' + needle,
                    1,
                )
                app_bg.write_text(bg)
                print("Added androidx.biometric to app/build.gradle")

    return 0
if __name__ == "__main__":
    sys.exit(main())
