/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// RESTORED complete tree from last green deploy + SuperAdminSchoolsIdRoute.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SchoolApplicationRouteImport } from './routes/school-application'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminExaminationsRouteImport } from './routes/admin.examinations'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminLevelsRouteImport } from './routes/admin.levels'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminSemestersRouteImport } from './routes/admin.semesters'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'
import { Route as AdminStudentImportRouteImport } from './routes/admin.student-import'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerApprovalsRouteImport } from './routes/officer.approvals'
import { Route as OfficerIntegrityRouteImport } from './routes/officer.integrity'
import { Route as OfficerLiveExamsRouteImport } from './routes/officer.live-exams'
import { Route as OfficerNotificationsRouteImport } from './routes/officer.notifications'
import { Route as OfficerProfileRouteImport } from './routes/officer.profile'
import { Route as OfficerResultsRouteImport } from './routes/officer.results'
import { Route as OfficerSettingsRouteImport } from './routes/officer.settings'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentExaminationsRouteImport } from './routes/student.examinations'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminApplicationsRouteImport } from './routes/super-admin.applications'
import { Route as SuperAdminAuditLogsRouteImport } from './routes/super-admin.audit-logs'
import { Route as SuperAdminExaminationsRouteImport } from './routes/super-admin.examinations'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminProfileRouteImport } from './routes/super-admin.profile'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin.schools'
import { Route as SuperAdminSchoolsIdRouteImport } from './routes/super-admin.schools.$id'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSubscriptionsRouteImport } from './routes/super-admin.subscriptions'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherExamSecurityRouteImport } from './routes/teacher.exam-security'
import { Route as TeacherExaminationsRouteImport } from './routes/teacher.examinations'
import { Route as TeacherIntegrityRouteImport } from './routes/teacher.integrity'
import { Route as TeacherLiveExamsRouteImport } from './routes/teacher.live-exams'
import { Route as TeacherMarkingRouteImport } from './routes/teacher.marking'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherSubmissionsRouteImport } from './routes/teacher.submissions'
import { Route as StudentExamIdRouteImport } from './routes/student.exam.$id'
import { Route as TeacherExamPaperIdRouteImport } from './routes/teacher.exam-paper.$id'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({ id: '/application-status', path: '/application-status', getParentRoute: () => rootRouteImport } as any)
const FeaturesRoute = FeaturesRouteImport.update({ id: '/features', path: '/features', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const OfficerRoute = OfficerRouteImport.update({ id: '/officer', path: '/officer', getParentRoute: () => rootRouteImport } as any)
const PricingRoute = PricingRouteImport.update({ id: '/pricing', path: '/pricing', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const SchoolApplicationRoute = SchoolApplicationRouteImport.update({ id: '/school-application', path: '/school-application', getParentRoute: () => rootRouteImport } as any)
const StudentRoute = StudentRouteImport.update({ id: '/student', path: '/student', getParentRoute: () => rootRouteImport } as any)
const SuperAdminRoute = SuperAdminRouteImport.update({ id: '/super-admin', path: '/super-admin', getParentRoute: () => rootRouteImport } as any)
const SupportRoute = SupportRouteImport.update({ id: '/support', path: '/support', getParentRoute: () => rootRouteImport } as any)
const TeacherRoute = TeacherRouteImport.update({ id: '/teacher', path: '/teacher', getParentRoute: () => rootRouteImport } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({ id: '/auth/callback', path: '/auth/callback', getParentRoute: () => rootRouteImport } as any)

const AdminIndexRoute = AdminIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AdminRoute } as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({ id: '/courses', path: '/courses', getParentRoute: () => AdminRoute } as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({ id: '/departments', path: '/departments', getParentRoute: () => AdminRoute } as any)
const AdminExaminationsRoute = AdminExaminationsRouteImport.update({ id: '/examinations', path: '/examinations', getParentRoute: () => AdminRoute } as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({ id: '/faculties', path: '/faculties', getParentRoute: () => AdminRoute } as any)
const AdminLevelsRoute = AdminLevelsRouteImport.update({ id: '/levels', path: '/levels', getParentRoute: () => AdminRoute } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => AdminRoute } as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({ id: '/officers', path: '/officers', getParentRoute: () => AdminRoute } as any)
const AdminProfileRoute = AdminProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => AdminRoute } as any)
const AdminReportsRoute = AdminReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AdminRoute } as any)
const AdminResultsRoute = AdminResultsRouteImport.update({ id: '/results', path: '/results', getParentRoute: () => AdminRoute } as any)
const AdminSemestersRoute = AdminSemestersRouteImport.update({ id: '/semesters', path: '/semesters', getParentRoute: () => AdminRoute } as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({ id: '/sessions', path: '/sessions', getParentRoute: () => AdminRoute } as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AdminRoute } as any)
const AdminStructureRoute = AdminStructureRouteImport.update({ id: '/structure', path: '/structure', getParentRoute: () => AdminRoute } as any)
const AdminStudentImportRoute = AdminStudentImportRouteImport.update({ id: '/student-import', path: '/student-import', getParentRoute: () => AdminRoute } as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({ id: '/teachers', path: '/teachers', getParentRoute: () => AdminRoute } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({ id: '/users', path: '/users', getParentRoute: () => AdminRoute } as any)

const OfficerIndexRoute = OfficerIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => OfficerRoute } as any)
const OfficerApprovalsRoute = OfficerApprovalsRouteImport.update({ id: '/approvals', path: '/approvals', getParentRoute: () => OfficerRoute } as any)
const OfficerIntegrityRoute = OfficerIntegrityRouteImport.update({ id: '/integrity', path: '/integrity', getParentRoute: () => OfficerRoute } as any)
const OfficerLiveExamsRoute = OfficerLiveExamsRouteImport.update({ id: '/live-exams', path: '/live-exams', getParentRoute: () => OfficerRoute } as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => OfficerRoute } as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => OfficerRoute } as any)
const OfficerResultsRoute = OfficerResultsRouteImport.update({ id: '/results', path: '/results', getParentRoute: () => OfficerRoute } as any)
const OfficerSettingsRoute = OfficerSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => OfficerRoute } as any)

const StudentIndexRoute = StudentIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => StudentRoute } as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({ id: '/courses', path: '/courses', getParentRoute: () => StudentRoute } as any)
const StudentExaminationsRoute = StudentExaminationsRouteImport.update({ id: '/examinations', path: '/examinations', getParentRoute: () => StudentRoute } as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => StudentRoute } as any)
const StudentProfileRoute = StudentProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => StudentRoute } as any)
const StudentResultsRoute = StudentResultsRouteImport.update({ id: '/results', path: '/results', getParentRoute: () => StudentRoute } as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => StudentRoute } as any)
const StudentExamIdRoute = StudentExamIdRouteImport.update({ id: '/exam/$id', path: '/exam/$id', getParentRoute: () => StudentRoute } as any)

const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminApplicationsRoute = SuperAdminApplicationsRouteImport.update({ id: '/applications', path: '/applications', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminAuditLogsRoute = SuperAdminAuditLogsRouteImport.update({ id: '/audit-logs', path: '/audit-logs', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminExaminationsRoute = SuperAdminExaminationsRouteImport.update({ id: '/examinations', path: '/examinations', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminProfileRoute = SuperAdminProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({ id: '/schools', path: '/schools', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminSchoolsIdRoute = SuperAdminSchoolsIdRouteImport.update({ id: '/schools/$id', path: '/schools/$id', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminSubscriptionsRoute = SuperAdminSubscriptionsRouteImport.update({ id: '/subscriptions', path: '/subscriptions', getParentRoute: () => SuperAdminRoute } as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({ id: '/users', path: '/users', getParentRoute: () => SuperAdminRoute } as any)

const TeacherIndexRoute = TeacherIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => TeacherRoute } as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({ id: '/courses', path: '/courses', getParentRoute: () => TeacherRoute } as any)
const TeacherExamSecurityRoute = TeacherExamSecurityRouteImport.update({ id: '/exam-security', path: '/exam-security', getParentRoute: () => TeacherRoute } as any)
const TeacherExaminationsRoute = TeacherExaminationsRouteImport.update({ id: '/examinations', path: '/examinations', getParentRoute: () => TeacherRoute } as any)
const TeacherIntegrityRoute = TeacherIntegrityRouteImport.update({ id: '/integrity', path: '/integrity', getParentRoute: () => TeacherRoute } as any)
const TeacherLiveExamsRoute = TeacherLiveExamsRouteImport.update({ id: '/live-exams', path: '/live-exams', getParentRoute: () => TeacherRoute } as any)
const TeacherMarkingRoute = TeacherMarkingRouteImport.update({ id: '/marking', path: '/marking', getParentRoute: () => TeacherRoute } as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => TeacherRoute } as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => TeacherRoute } as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({ id: '/question-bank', path: '/question-bank', getParentRoute: () => TeacherRoute } as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({ id: '/results', path: '/results', getParentRoute: () => TeacherRoute } as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => TeacherRoute } as any)
const TeacherSubmissionsRoute = TeacherSubmissionsRouteImport.update({ id: '/submissions', path: '/submissions', getParentRoute: () => TeacherRoute } as any)
const TeacherExamPaperIdRoute = TeacherExamPaperIdRouteImport.update({ id: '/exam-paper/$id', path: '/exam-paper/$id', getParentRoute: () => TeacherRoute } as any)

const AdminRouteChildren = {
  AdminIndexRoute, AdminCoursesRoute, AdminDepartmentsRoute, AdminExaminationsRoute,
  AdminFacultiesRoute, AdminLevelsRoute, AdminNotificationsRoute, AdminOfficersRoute,
  AdminProfileRoute, AdminReportsRoute, AdminResultsRoute, AdminSemestersRoute,
  AdminSessionsRoute, AdminSettingsRoute, AdminStructureRoute, AdminStudentImportRoute,
  AdminTeachersRoute, AdminUsersRoute,
}
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const OfficerRouteChildren = {
  OfficerIndexRoute, OfficerApprovalsRoute, OfficerIntegrityRoute, OfficerLiveExamsRoute,
  OfficerNotificationsRoute, OfficerProfileRoute, OfficerResultsRoute, OfficerSettingsRoute,
}
const OfficerRouteWithChildren = OfficerRoute._addFileChildren(OfficerRouteChildren)

const StudentRouteChildren = {
  StudentCoursesRoute, StudentExaminationsRoute, StudentNotificationsRoute, StudentProfileRoute,
  StudentResultsRoute, StudentSettingsRoute, StudentIndexRoute, StudentExamIdRoute,
}
const StudentRouteWithChildren = StudentRoute._addFileChildren(StudentRouteChildren)

const SuperAdminRouteChildren = {
  SuperAdminApplicationsRoute, SuperAdminAuditLogsRoute, SuperAdminExaminationsRoute,
  SuperAdminNotificationsRoute, SuperAdminProfileRoute, SuperAdminReportsRoute,
  SuperAdminSchoolsRoute, SuperAdminSchoolsIdRoute, SuperAdminSettingsRoute,
  SuperAdminSubscriptionsRoute, SuperAdminUsersRoute, SuperAdminIndexRoute,
}
const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(SuperAdminRouteChildren)

const TeacherRouteChildren = {
  TeacherCoursesRoute, TeacherExamSecurityRoute, TeacherExaminationsRoute, TeacherIntegrityRoute,
  TeacherLiveExamsRoute, TeacherMarkingRoute, TeacherNotificationsRoute, TeacherProfileRoute,
  TeacherQuestionBankRoute, TeacherResultsRoute, TeacherSettingsRoute, TeacherSubmissionsRoute,
  TeacherIndexRoute, TeacherExamPaperIdRoute,
}
const TeacherRouteWithChildren = TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren = {
  IndexRoute, AboutRoute, AdminRoute: AdminRouteWithChildren, ApplicationStatusRoute,
  FeaturesRoute, ForgotPasswordRoute, LoginRoute, OfficerRoute: OfficerRouteWithChildren,
  PricingRoute, PrivacyRoute, ResetPasswordRoute, SchoolApplicationRoute,
  StudentRoute: StudentRouteWithChildren, SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute, TeacherRoute: TeacherRouteWithChildren, AuthCallbackRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<any>()
